#!/bin/bash
#
# Author: Anandan - andy.compeer@gmail.com
#                 - andy@grooveshark.com
WD=$(dirname $(readlink -f $0))
cd $WD
BIN_DIR="/usr/local/bin"
if [ ! -z "$1" ]
then
    BIN_DIR=$1
fi
ls -l $WD | grep ^-rwx | awk '{print $NF}' | xargs -I {} ln -s $WD/{} $BIN_DIR
