#!/bin/bash
#
# Author: Anandan - andy.compeer@gmail.com
#                 - andy@grooveshark.com

VPN_NAME=""
UP_DOWN="up"
if [[ ! -z "$1" && ("$1" == "up" || "$1" == "down") ]]
then
    UP_DOWN=$1
fi
if [ ! -z "$2" ]
then
    VPN_NAME=$2
fi
UUID=$(nmcli con list | grep -i "$VPN_NAME.*vpn" | awk '{print $2}')
nmcli con "$UP_DOWN" uuid $UUID
