#!/bin/bash
#
# Author: Anandan - andy.compeer@gmail.com
#                 - andy@grooveshark.com

if [ -z "${1}" ]
then
    echo "Usage: gitdiff <part-of-file-name>"
    echo "Please use it under a git root directory"
    exit 1
fi
part_file_name=${1}
filepath=$(git st | grep modified | awk -F" " '{print $2}' | grep -i ${1})
if [ ! -z "${filepath}" ]
then
    git diff ${filepath}
else
    echo "Nothing to show."
fi
